# Generated by Erlang.mk. Edit at your own risk!

src/rabbit_tracing_consumer_sup.erl:: /mnt/c/Users/WN00086506/dev/rabbitmq-stamper-exchange/deps/rabbit_common/include/rabbit.hrl /mnt/c/Users/WN00086506/dev/rabbitmq-stamper-exchange/deps/rabbit_common/include/resource.hrl; @touch $@
src/rabbit_tracing_sup.erl:: /mnt/c/Users/WN00086506/dev/rabbitmq-stamper-exchange/deps/rabbit_common/include/rabbit.hrl /mnt/c/Users/WN00086506/dev/rabbitmq-stamper-exchange/deps/rabbit_common/include/resource.hrl; @touch $@

COMPILE_FIRST +=
